# Generated by Antigravity
# Use a Python image with uv pre-installed
FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim

# Set the working directory
WORKDIR /app

# Enable bytecode compilation
ENV UV_COMPILE_BYTECODE=1

# Copy from the cache instead of linking since it's a container
ENV UV_LINK_MODE=copy

# Install the project's dependencies
# We copy explicitly since Cloud Build might not have BuildKit enabled
COPY uv.lock pyproject.toml ./
RUN uv sync --frozen --no-install-project --no-dev

# Place /app/.venv/bin/ at the beginning of the PATH
ENV PATH="/app/.venv/bin:$PATH"

# Copy the rest of the application code
COPY . .

# Run the MCP server
CMD ["python", "server.py"]
